github yml file setting.....

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -43,13 +43,25 @@ jobs:
             cd /home/opc/app 
             
             sudo pkill -9 -f 'java -jar' || true
+            sleep 3
+            
+            ls -t *.jar | tail -n +2 | xargs rm -f || true
+        
             
             sudo sync && echo 3 | sudo tee /proc/sys/vm/drop_caches
             
             sleep 10
             
             echo "새 애플리케이션 배포 시작"
-            nohup java -Xmx384m -Xms384m -jar *SNAPSHOT.jar > app.log 2>&1 &
+            nohup java -Xmx256m -Xms256m -jar *.jar > app.log 2>&1 &
             
-            sleep 2
-            ps -ef | grep java
+            sleep 5
+                        if pgrep -f .jar > /dev/null
+                        then
+                          echo "Application started successfully!"
+                          exit 0
+                        else
+                          echo "Application failed to start. Check app.log"
+                          cat app.log
+                          exit 1
+                        fi
